CREATE TABLE heroes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        alias VARCHAR(100),
                        universe VARCHAR(50) NOT NULL,         -- enum Universe como texto
                        power_level INT NOT NULL,
                        active BOOLEAN NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_hero_name UNIQUE (name)
);