INSERT INTO heroes (name, alias, universe, power_level, active, created_at, updated_at)
VALUES
    ('Superman',        'Clark Kent',        'DC',      95, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Batman',          'Bruce Wayne',       'DC',      85, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Wonder Woman',    'Diana Prince',      'DC',      92, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Flash',           'Barry Allen',       'DC',      90, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Aquaman',         'Arthur Curry',      'DC',      88, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Green Lantern',   'Hal Jordan',        'DC',      89, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cyborg',          'Victor Stone',      'DC',      86, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Green Arrow',     'Oliver Queen',      'DC',      80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Shazam',          'Billy Batson',      'DC',      93, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supergirl',       'Kara Zor-El',       'DC',      90, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Nightwing',       'Dick Grayson',      'DC',      82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Robin',           'Damian Wayne',      'DC',      78, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Batgirl',         'Barbara Gordon',    'DC',      80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Hawkman',         'Carter Hall',       'DC',      82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Hawkgirl',        'Shiera Hall',       'DC',      82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Martian Manhunter','J''onn J''onzz',   'DC',      94, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Black Canary',    'Dinah Lance',       'DC',      80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Zatanna',         'Zatanna Zatara',    'DC',      88, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Constantine',     'John Constantine',  'DC',      84, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Blue Beetle',     'Jaime Reyes',       'DC',      83, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Doctor Fate',     'Kent Nelson',       'DC',      93, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Red Hood',        'Jason Todd',        'DC',      81, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Starfire',        'Koriand''r',        'DC',      86, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Raven',           'Rachel Roth',       'DC',      88, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Beast Boy',       'Garfield Logan',    'DC',      80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Kid Flash',       'Wally West',        'DC',      85, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Spider-Man',      'Peter Parker',      'MARVEL',  88, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Iron Man',        'Tony Stark',        'MARVEL',  90, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Captain America', 'Steve Rogers',      'MARVEL',  88, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Thor',            'Thor Odinson',      'MARVEL',  95, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Hulk',            'Bruce Banner',      'MARVEL',  96, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Black Widow',     'Natasha Romanoff',  'MARVEL',  82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Hawkeye',         'Clint Barton',      'MARVEL',  80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Scarlet Witch',   'Wanda Maximoff',    'MARVEL',  95, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Vision',          'Vision',            'MARVEL',  92, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Falcon',          'Sam Wilson',        'MARVEL',  82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Winter Soldier',  'Bucky Barnes',      'MARVEL',  84, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Black Panther',   'T''Challa',         'MARVEL',  90, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Doctor Strange',  'Stephen Strange',   'MARVEL',  94, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Captain Marvel',  'Carol Danvers',     'MARVEL',  94, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Ant-Man',         'Scott Lang',        'MARVEL',  80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Wasp',            'Hope van Dyne',     'MARVEL',  82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Star-Lord',       'Peter Quill',       'MARVEL',  81, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Gamora',          'Gamora',            'MARVEL',  86, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Drax',            'Drax the Destroyer','MARVEL',  85, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rocket',          'Rocket Raccoon',    'MARVEL',  82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Groot',           'Groot',             'MARVEL',  84, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Nebula',          'Nebula',            'MARVEL',  83, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('War Machine',     'James Rhodes',      'MARVEL',  85, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('She-Hulk',        'Jennifer Walters',  'MARVEL',  90, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Spider-Gwen',     'Gwen Stacy',        'MARVEL',  84, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Miles Morales',   'Miles Morales',     'MARVEL',  86, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Daredevil',       'Matt Murdock',      'MARVEL',  84, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Luke Cage',       'Luke Cage',         'MARVEL',  86, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Jessica Jones',   'Jessica Jones',     'MARVEL',  83, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Iron Fist',       'Danny Rand',        'MARVEL',  83, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Punisher',        'Frank Castle',      'MARVEL',  82, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Storm',           'Ororo Munroe',      'MARVEL',  90, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Wolverine',       'Logan',             'MARVEL',  92, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cyclops',         'Scott Summers',     'MARVEL',  86, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Jean Grey',       'Jean Grey',         'MARVEL',  94, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Beast',           'Hank McCoy',        'MARVEL',  85, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rogue',           'Anna Marie',        'MARVEL',  88, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Gambit',          'Remy LeBeau',       'MARVEL',  85, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Professor X',     'Charles Xavier',    'MARVEL',  93, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Magneto',         'Erik Lehnsherr',    'MARVEL',  95, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);